/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import IProov from 'iproov-react-native';
import { ApiClient } from './apiClient.js'
import uuid from 'react-native-uuid'

export default class App extends Component {

  state = {
    message: '--'
  };

  config = {
    baseUrl : 'https://beta.rp.secure.iproov.me/api/v2/',
    apiKey: '342a9ecc7a38610ab08620110c6250812d2a6c1d',
    secret: 'cefd2abf7aa3be084e1e8892fbdd262eb1553d03'
  }

  apiClient = new ApiClient(this.config)

  componentDidMount() {
    //this.registerListeners()
  }

  launchIProov = () => {
    this.apiClient.getToken('liveness', 'enrol', uuidv4()).then(data => {
      console.log('Launching iProov with token: ' + data.token);

      let options = new IProov.Options()
      options.ui.filter = 'shaded'

      IProov.launch(this.config.baseUrl, data.token, options, (e) => this.eventHandler(e));
    })
  }

  eventHandler(iproovEvent) {
    console.log(iproovEvent)
    this.setState({
      message: JSON.stringify(iproovEvent)
    })
  }


  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆IProovReactNative example☆</Text>
    
        <Button
          onPress={this.launchIProov}
          title='Launch'
          color='#841584'/>
          <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

function uuidv4() {
  console.log(uuid.v4());
  return uuid.v4()
}