require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks!

target 'example' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'exampleTests' do
    inherit! :complete
    # Pods for testing
  end

end

# Workaround for dynamic frameworks:
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !['iProov'].include?(pod.name)
      def pod.static_framework?;
      true
    end
    def pod.build_type;
    Pod::BuildType.static_library
  end
end
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Solves issue with C++ boost -> https://github.com/facebook/react-native/issues/37748
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
    end
  end
  system("sed -i -e 's/ \|$/ ||/g' ../node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp")
  end
end
